[project]
name = demi boi
target region = "PNW"
legal team = (vacant)
; OOPS

[fruit "Apple"]
trademark issues = foreseeable
taste = known

[fruit "Raspberry"]
anticipated problems  ="logistics (fragile fruit)"
Trademark Issues=\
 possible

[fruit.raspberry.proponents.fred]
date = 2026-05-15, 21:25 +0900
comment = "I like being queer."

# folding: Is "\\\\\nn" interpreted as "\\n" or "\n"?
#   Or does "\\\\" prevent folding?
editor  =My name may contain a \\
newline.